### ISSUE TITLE
Error when I trying to download theme.

### ISSUE THREAD

**Issue by llait** [csaunders/phoenix#40]
This is me `config.yml`
```
production:
  theme_id:
  access_token:
  store:
  ignore_files:
  - config/settings.html
  bucket_size: 40
  refill_rate: 2
  concurrency: 2
development:
  theme_id: 10545104
  access_token: 57a4b412f77111111111111
  store: store.myshopify.com
  ignore_files:
  - config/settings.html
  bucket_size: 40
  refill_rate: 2
```

This is error log: 
```
➜  Pre-Order-Setsuna-Pluto git:(master) theme-manipulate download
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b7b3]

goroutine 20 [running]:
runtime.panic(0x2ea200, 0x4cdd44)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
github.com/csaunders/phoenix.ThemeClient.query(0x0, 0x0, 0x0, 0x0, 0x0, 0xc208036b72, 0xe, 0x0, 0x0, 0x0, ...)
	/Users/csaunders/development/golang/src/github.com/csaunders/phoenix/theme_client.go:187 +0x573
github.com/csaunders/phoenix.func·012()
	/Users/csaunders/development/golang/src/github.com/csaunders/phoenix/theme_client.go:111 +0x4f
created by github.com/csaunders/phoenix.ThemeClient.AssetList
	/Users/csaunders/development/golang/src/github.com/csaunders/phoenix/theme_client.go:122 +0xb1

goroutine 16 [chan receive]:
main.main()
	/Users/csaunders/development/golang/src/github.com/csaunders/phoenix/cmd/theme-manipulate/main.go:74 +0x1d3

goroutine 19 [finalizer wait]:
runtime.park(0x18b60, 0x4d1350, 0x4cfe09)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x4d1350, 0x4cfe09)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 21 [runnable]:
main.downloadAllFiles(0xc208005020, 0xc208004fc0)
	/Users/csaunders/development/golang/src/github.com/csaunders/phoenix/cmd/theme-manipulate/download.go:24
created by main.DownloadOperation
	/Users/csaunders/development/golang/src/github.com/csaunders/phoenix/cmd/theme-manipulate/download.go:16 +0x99
```
